#!/usr/bin/with-contenv bash

echo 'root:58a56c452c' | chpasswd


echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u shellinabox)
User gid:    $(id -g shellinabox)
-------------------------------------
"
